from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(667, 382)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(9, 5, 639, 324))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.encryption_mode = QtWidgets.QRadioButton(parent=self.widget)
        self.encryption_mode.setObjectName("encryption_mode")
        self.verticalLayout.addWidget(self.encryption_mode)
        self.decryption_mode = QtWidgets.QRadioButton(parent=self.widget)
        self.decryption_mode.setObjectName("decryption_mode")
        self.verticalLayout.addWidget(self.decryption_mode)
        self.horizontalLayout_6.addLayout(self.verticalLayout)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.browse_files = QtWidgets.QToolButton(parent=self.widget)
        self.browse_files.setObjectName("browse_files")
        self.horizontalLayout_5.addWidget(self.browse_files)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.choose_certificate = QtWidgets.QPushButton(parent=self.widget)
        self.choose_certificate.setObjectName("choose_certificate")
        self.verticalLayout_2.addWidget(self.choose_certificate)
        self.decryption = QtWidgets.QPushButton(parent=self.widget)
        self.decryption.setObjectName("decryption")
        self.verticalLayout_2.addWidget(self.decryption)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)
        self.execute = QtWidgets.QPushButton(parent=self.widget)
        self.execute.setObjectName("execute")
        self.horizontalLayout_5.addWidget(self.execute)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_5)
        self.gost_list = QtWidgets.QListWidget(parent=self.widget)
        self.gost_list.setObjectName("gost_list")
        item = QtWidgets.QListWidgetItem()
        self.gost_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.gost_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.gost_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.gost_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.gost_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.gost_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.gost_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.gost_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.gost_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.gost_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.gost_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.gost_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.gost_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.gost_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.gost_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.gost_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.gost_list.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.gost_list.addItem(item)
        self.horizontalLayout_6.addWidget(self.gost_list)
        self.gridLayout.addLayout(self.horizontalLayout_6, 0, 0, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.file_label = QtWidgets.QLabel(parent=self.widget)
        self.file_label.setObjectName("file_label")
        self.horizontalLayout.addWidget(self.file_label)
        self.filename_label = QtWidgets.QLabel(parent=self.widget)
        self.filename_label.setObjectName("filename_label")
        self.horizontalLayout.addWidget(self.filename_label)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.cert_label = QtWidgets.QLabel(parent=self.widget)
        self.cert_label.setObjectName("cert_label")
        self.horizontalLayout_2.addWidget(self.cert_label)
        self.cert_label_2 = QtWidgets.QLabel(parent=self.widget)
        self.cert_label_2.setObjectName("cert_label_2")
        self.horizontalLayout_2.addWidget(self.cert_label_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.method_label = QtWidgets.QLabel(parent=self.widget)
        self.method_label.setObjectName("method_label")
        self.horizontalLayout_3.addWidget(self.method_label)
        self.method_label_2 = QtWidgets.QLabel(parent=self.widget)
        self.method_label_2.setObjectName("method_label_2")
        self.horizontalLayout_3.addWidget(self.method_label_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.key_label = QtWidgets.QLabel(parent=self.widget)
        self.key_label.setObjectName("key_label")
        self.horizontalLayout_4.addWidget(self.key_label)
        self.key_label_2 = QtWidgets.QLabel(parent=self.widget)
        self.key_label_2.setObjectName("key_label_2")
        self.horizontalLayout_4.addWidget(self.key_label_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.progress_bar = QtWidgets.QProgressBar(parent=self.widget)
        self.progress_bar.setProperty("value", 24)
        self.progress_bar.setObjectName("progress_bar")
        self.verticalLayout_3.addWidget(self.progress_bar)
        self.gridLayout.addLayout(self.verticalLayout_3, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 667, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.file_label.setBuddy(self.browse_files)
        self.cert_label.setBuddy(self.choose_certificate)
        self.method_label.setBuddy(self.gost_list)
        self.key_label.setBuddy(self.decryption)

        self.retranslateUi(MainWindow)
        self.choose_certificate.clicked.connect(self.gost_list.scrollToTop) # type: ignore
        self.execute.clicked.connect(self.progress_bar.reset) # type: ignore
        self.browse_files.clicked.connect(self.filename_label.clear) # type: ignore
        self.decryption.clicked.connect(self.key_label_2.clear) # type: ignore
        self.choose_certificate.clicked.connect(self.cert_label_2.clear) # type: ignore
        self.gost_list.itemClicked['QListWidgetItem*'].connect(self.method_label_2.clear) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.encryption_mode, self.decryption_mode)
        MainWindow.setTabOrder(self.decryption_mode, self.browse_files)
        MainWindow.setTabOrder(self.browse_files, self.choose_certificate)
        MainWindow.setTabOrder(self.choose_certificate, self.gost_list)
        MainWindow.setTabOrder(self.gost_list, self.decryption)
        MainWindow.setTabOrder(self.decryption, self.execute)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "OpenSSL(GOST) tools"))
        self.encryption_mode.setText(_translate("MainWindow", "Encryption mode"))
        self.decryption_mode.setText(_translate("MainWindow", "Decryption mode"))
        self.browse_files.setText(_translate("MainWindow", "Choose a file"))
        self.choose_certificate.setText(_translate("MainWindow", "Provide CERT"))
        self.decryption.setText(_translate("MainWindow", "Provide key"))
        self.execute.setText(_translate("MainWindow", "Execute"))
        self.gost_list.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Список всех вариантов шифрования описанных в ГОСТ 34чето-там</p></body></html>"))
        __sortingEnabled = self.gost_list.isSortingEnabled()
        self.gost_list.setSortingEnabled(False)
        item = self.gost_list.item(0)
        item.setText(_translate("MainWindow", "-gost-89"))
        item = self.gost_list.item(1)
        item.setText(_translate("MainWindow", "-gost-89-cbc"))
        item = self.gost_list.item(2)
        item.setText(_translate("MainWindow", "-gost-89-cnt"))
        item = self.gost_list.item(3)
        item.setText(_translate("MainWindow", "-gost-89-cnt-12"))
        item = self.gost_list.item(4)
        item.setText(_translate("MainWindow", "-kuznyechik-cbc"))
        item = self.gost_list.item(5)
        item.setText(_translate("MainWindow", "-kuznyechik-cfb"))
        item = self.gost_list.item(6)
        item.setText(_translate("MainWindow", "-kuznyechik-ctr"))
        item = self.gost_list.item(7)
        item.setText(_translate("MainWindow", "-kuznyechik-ctr-acpkm"))
        item = self.gost_list.item(8)
        item.setText(_translate("MainWindow", "-kuznyechik-ctr-acpkm-omac"))
        item = self.gost_list.item(9)
        item.setText(_translate("MainWindow", "-kuznyechik-ecb"))
        item = self.gost_list.item(10)
        item.setText(_translate("MainWindow", "-kuznyechik-kexp15"))
        item = self.gost_list.item(11)
        item.setText(_translate("MainWindow", "-kuznyechik-ofb"))
        item = self.gost_list.item(12)
        item.setText(_translate("MainWindow", "-magma-cbc"))
        item = self.gost_list.item(13)
        item.setText(_translate("MainWindow", "-magma-ctr"))
        item = self.gost_list.item(14)
        item.setText(_translate("MainWindow", "-magma-ctr-acpkm"))
        item = self.gost_list.item(15)
        item.setText(_translate("MainWindow", "-magma-ctr-acpkm-omac"))
        item = self.gost_list.item(16)
        item.setText(_translate("MainWindow", "-magma-ecb"))
        item = self.gost_list.item(17)
        item.setText(_translate("MainWindow", "-magma-kexp15"))
        self.gost_list.setSortingEnabled(__sortingEnabled)
        self.file_label.setText(_translate("MainWindow", "Selected file: "))
        self.filename_label.setText(_translate("MainWindow", "FILENAME"))
        self.cert_label.setText(_translate("MainWindow", "Selected CERT: "))
        self.cert_label_2.setText(_translate("MainWindow", "CERTIFICATE"))
        self.method_label.setText(_translate("MainWindow", "Selected method: "))
        self.method_label_2.setText(_translate("MainWindow", "METHOD"))
        self.key_label.setText(_translate("MainWindow", "Selected KEY: "))
        self.key_label_2.setText(_translate("MainWindow", "KEY"))
