from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_simple_tool(object):
    def setupUi(self, simple_tool):
        simple_tool.setObjectName("simple_tool")
        simple_tool.resize(602, 182)
        self.widget = QtWidgets.QWidget(parent=simple_tool)
        self.widget.setGeometry(QtCore.QRect(15, 16, 563, 152))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.text1_label = QtWidgets.QLabel(parent=self.widget)
        self.text1_label.setObjectName("text1_label")
        self.verticalLayout.addWidget(self.text1_label)
        self.text2_label = QtWidgets.QLabel(parent=self.widget)
        self.text2_label.setObjectName("text2_label")
        self.verticalLayout.addWidget(self.text2_label)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_choose = QtWidgets.QPushButton(parent=self.widget)
        self.label_choose.setObjectName("label_choose")
        self.horizontalLayout_3.addWidget(self.label_choose)
        self.label_execute = QtWidgets.QPushButton(parent=self.widget)
        self.label_execute.setObjectName("label_execute")
        self.horizontalLayout_3.addWidget(self.label_execute)
        self.gridLayout.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_file = QtWidgets.QLabel(parent=self.widget)
        self.label_file.setObjectName("label_file")
        self.horizontalLayout_2.addWidget(self.label_file)
        self.label_filename = QtWidgets.QLabel(parent=self.widget)
        self.label_filename.setObjectName("label_filename")
        self.horizontalLayout_2.addWidget(self.label_filename)
        self.gridLayout.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)
        self.progress_bar = QtWidgets.QProgressBar(parent=self.widget)
        self.progress_bar.setProperty("value", 100)
        self.progress_bar.setObjectName("progress_bar")
        self.gridLayout.addWidget(self.progress_bar, 3, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_result = QtWidgets.QLabel(parent=self.widget)
        self.label_result.setObjectName("label_result")
        self.horizontalLayout.addWidget(self.label_result)
        self.result_path = QtWidgets.QLabel(parent=self.widget)
        self.result_path.setObjectName("result_path")
        self.horizontalLayout.addWidget(self.result_path)
        self.gridLayout.addLayout(self.horizontalLayout, 4, 0, 1, 1)
        self.label_file.setBuddy(self.label_choose)
        self.label_filename.setBuddy(self.label_choose)

        self.retranslateUi(simple_tool)
        self.label_execute.clicked.connect(self.progress_bar.reset) # type: ignore
        self.label_choose.clicked.connect(self.label_filename.clear) # type: ignore
        self.progress_bar.valueChanged['int'].connect(self.result_path.clear) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(simple_tool)
        simple_tool.setTabOrder(self.label_choose, self.label_execute)

    def retranslateUi(self, simple_tool):
        _translate = QtCore.QCoreApplication.translate
        simple_tool.setWindowTitle(_translate("simple_tool", "Encryptor"))
        self.text1_label.setText(_translate("simple_tool", "По умолчанию в упрощенном режиме при выборе файла с форматом .enc, он будет расшифрован."))
        self.text2_label.setText(_translate("simple_tool", "При выборе любого другого формата, будет произведено зашифрование!"))
        self.label_choose.setText(_translate("simple_tool", "Выберите файл"))
        self.label_execute.setText(_translate("simple_tool", "Исполнить"))
        self.label_file.setText(_translate("simple_tool", "Выбранный файл: "))
        self.label_filename.setText(_translate("simple_tool", "FILENAME"))
        self.label_result.setText(_translate("simple_tool", "Результат:"))
        self.result_path.setText(_translate("simple_tool", "PATH"))
